from django.db import models
from django.utils import timezone
# Create your models here.
class Stock_Phone_Parts_Price(models.Model):
	phone_name_num = models.CharField(max_length=20)
	phone_fix_elements_1 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_1 = models.CharField(max_length=10,default='0')
	phone_fix_elements_2 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_2 = models.CharField(max_length=10,default='0')
	phone_fix_elements_3 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_3 = models.CharField(max_length=10,default='0')
	phone_fix_elements_4 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_4 = models.CharField(max_length=10,default='0')
	phone_fix_elements_5 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_5 = models.CharField(max_length=10,default='0')
	phone_fix_elements_6 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_6 = models.CharField(max_length=10,default='0')
	phone_fix_elements_7 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_7 = models.CharField(max_length=10,default='0')
	phone_fix_elements_8 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_8 = models.CharField(max_length=10,default='0')
	phone_fix_elements_9 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_9 = models.CharField(max_length=10,default='0')
	phone_fix_elements_10 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_10 = models.CharField(max_length=10,default='0')
	phone_fix_elements_11 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_11 = models.CharField(max_length=10,default='0')
	phone_fix_elements_12 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_12 = models.CharField(max_length=10,default='0')
	phone_fix_elements_13 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_13 = models.CharField(max_length=10,default='0')
	phone_fix_elements_14 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_14 = models.CharField(max_length=10,default='0')
	phone_fix_elements_15 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_15 = models.CharField(max_length=10,default='0')
	phone_fix_elements_16 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_16 = models.CharField(max_length=10,default='0')
	phone_fix_elements_17 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_17 = models.CharField(max_length=10,default='0')
	phone_fix_elements_18 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_18 = models.CharField(max_length=10,default='0')
	phone_fix_elements_19 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_19 = models.CharField(max_length=10,default='0')
	phone_fix_elements_20 = models.CharField(max_length=10,default='none')
	phone_fix_elements_price_20 = models.CharField(max_length=10,default='0')
	alive = models.BooleanField(default=True)
	update_at = models.DateTimeField(default=timezone.now)